#!/usr/bin/env bash

# Point ~/.ssh/ssh_auth_sock symlink to correct value, for fixing dead keys on tmux
# logout. See https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
