name: base

# Stuff to install that isn't available on conda, for some reason:
# - Julia
# - npm install -g pyright, for Microsoft's Python language server

channels:
    - conda-forge
    - defaults
    - bioconda

dependencies:
    - bioconda::nextflow
    - black
    - conda-build
    - git
    - ipywidgets
    - isort
    - jupyterlab
    - lazygit
    - mamba
    - nb_conda_kernels
    - pip
    - pynvim
    - ripgrep
    - tmux

    # Fix for https://github.com/conda-forge/rabbitmq-server-feedstock/issues/14
    - conda-forge::ncurses
