name: base

# Stuff to install that isn't available on conda, for some reason:
# - Neovim
# - Julia

channels:
    - defaults
    - conda-forge

dependencies:
    - black
    - conda-build
    - git
    - ipywidgets
    - jupyter_console
    - jupyterlab
    - nb_conda_kernels
    - nodejs
    - pip
    - pynvim
    - qtconsole
    - ripgrep
    - tmux

    # Fix for https://github.com/conda-forge/rabbitmq-server-feedstock/issues/14
    - conda-forge::ncurses  

    - pip:
        - neovim-remote
        - spell
